// @ts-check
import { defineConfig } from '@vivliostyle/cli';

export default defineConfig([
    {
        title: "VTC MyPortal User Guide (Students)",
        author: "VTC MyPortal Team",
        language: "en",
        theme: "@vivliostyle/theme-techbook@^2.0.1",
        browser: "chrome@146.0.7680.153",
        image: "ghcr.io/vivliostyle/cli:10.5.0",
        size: "A4",
        toc: true,
        entry: [
            { rel: "contents" },
            "student/00-introduction.md",
            "student/01-login.md",
            "student/02-home.md",
            "student/03-navigation.md",
            "student/04-assistant.md",
            "student/05-calendar.md",
            "student/06-profile.md",
            "student/07-activities.md",
            "student/08-news.md",
            "student/09-resources.md",
            "student/10-appendix-quick-menu.md",
            "student/11-appendix-change-password.md",
        ],
        output: "User Guide (Students).pdf",
    },
    {
        title: "VTC MyPortal User Guide (Staff/Admin)",
        author: "VTC MyPortal Team",
        language: "en",
        theme: "@vivliostyle/theme-techbook@^2.0.1",
        browser: "chrome@146.0.7680.153",
        image: "ghcr.io/vivliostyle/cli:10.5.0",
        size: "A4",
        toc: true,
        entry: [
            { rel: "contents" },
            "staff/00-introduction.md",
            "staff/01-login.md",
            "staff/02-home.md",
            "staff/03-navigation.md",
            "staff/04-assistant.md",
            "staff/05-calendar.md",
            "staff/06-news.md",
            "staff/07-resources.md",
            "staff/08-dashboard-home.md",
            "staff/09-dashboard-navigation.md",
            "staff/10-dashboard-calendar.md",
            "staff/11-dashboard-academic.md",
            "staff/12-dashboard-students.md",
            "staff/13-dashboard-activities.md",
            "staff/14-dashboard-news.md",
            "staff/15-dashboard-resources.md",
            "staff/16-dashboard-system.md",
            "staff/17-appendix-quick-menu.md",
            "staff/18-appendix-change-password.md",
        ],
        output: "User Guide (Staff).pdf",
    },
]);
